spring:
  application:
    name: "Cookie's Front App"
    version: 0.1
    description: "Cookie's Front App that consumes REST requests and store a message in RabbitMq."
  main:
    banner-mode: "off"
  rabbitmq:
    host: "docker-rabbitmq"
    port: 5672
    username: "cookieMq"
    password: "very_secret_cookie_password"

developer:
  name: "CookieMr"
  email: "mr@cookie.inc"
  url: "https://github.com/cookieMr"

mr:
  cookie:
    queue:
      name: "insertMoviesQueue"
    backend:
      url: "http://docker-java-backend"
      port: 8082

server:
  port: 8081
  servlet:
    context-path: "/api"

---

spring:
  profiles: "local"
  rabbitmq:
    host: "localhost"
amazon:
  dynamodb:
    endpoint: "http://localhost:8000/"
mr:
  cookie:
    backend:
      url: "http://localhost"
